version: '3'

services: 
    app:
        build: 
            context: .
        environment: 
            PGUSER: postgres
            PGPASSWORD: example
            PGDATABASE: postgres
            PGPORT: 5432
            PGHOST: db
        ports: 
            - "4000:4000"
        depends_on: 
            - db
        tty: true
        volumes:
            - .:/app
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: postgres
            POSTGRESQL_USERNAME: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports: 
            - "5432:5432"
        restart: always
        volumes:
            - "pgdata:/var/lib/postgresql/data"
volumes: 
    pgdata: